version: '3.3'
services:
  wordpress:
    image: wordpress:4.8-apache
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_HOST=mysql
    
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret